### ISSUE TITLE
배열로 초/중/종성 분해 오류

### ISSUE THREAD

**Issue by gaon12** [gaon12/hangulpy#1]
1. 에러 반환

```python
char1 = '값'
print(split_hangul_char(char1))
```

이렇게 하면

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\uiharuchan\.conda\envs\libenvs\Lib\site-packages\hangulpy\hangul_split.py", line 26, in split_hangul_char
    return [CHOSUNG_LIST[chosung_index]] + jungsung_decomposed + jongsung_decomposed
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate list (not "tuple") to list
```

이렇게 뜹니다.

2. 엉뚱한 값 반환
```python
char2 = 'ㅘ'
print(split_hangul_char(char2))
```

이렇게 하면 `['ㅗ', 'ㅏ']`로 반환되어야 하는데 `['ㅘ']` 이렇게 반환이 됩니다.

마찬가지로

```python
char3 = 'ㄵ'
print(split_hangul_char(char3))
```

이렇게 하면 `['ㄴ', 'ㅈ']`로 반환되어야 하는데 `['ㄵ']` 이렇게 반환이 됩니다.

3. 문자 1개(문자)가 아닌 여러개 문자(문자열)은 오류가 반환됩니다. `split_hangul_string` 함수를 만듭시다.

**Comment by gaon12** [comment]
f50064ce7850b4690403ba650e087d1457f11991 커밋으로 수정했습니다!
